#!/bin/bash

pakname=${1}
distro=`lsb_release -cs`
dir=${PWD}

mkdir ${pakname}
cd ${pakname}
dh_make -s --native --templates ${dir}/templates -c bsd \
        -p ${pakname}_1.0 --rulesformat dh7
rm -f debian/{*.ex,*.EX,README*,changelog,docs}
sed -i 's,<url://example.com>,http://github.com/pkt/pkt-pkg-bundles,g' debian/copyright
sed -i '4,8d'                      debian/copyright
sed -i '/^# Please also look/d'    debian/copyright
sed -i '/^# different copyright/d' debian/copyright

editor debian/control
dch --create --package ${pakname} --newversion 1.0 --distribution ${distro}
sed -i 's/ (Closes.*$//' debian/changelog
